### PR TITLE
Gitignore fix

### PR DESCRIPTION
**Pull request by mevolkan**
afew updates and fixes

### CODE REVIEW

**Comment by booleanhunter** [comment]
Hi @mevolkan , can you check this PR once more? Looks like it's exactly same like the earlier one. Let me know if you have any questions!

**Comment by mevolkan** [comment]
Hi @booleanhunter , I switched to an earlier commit then made a pull request, not sure what's necessary, i can switch it to another

**Comment by booleanhunter** [comment]
@mevolkan  Okay, let's go step by step, I will guide you through it.

Can you begin by describing how you switched to the earlier commit? What was the specific git command that you typed?

**Comment by mevolkan** [comment]
this is the command I used git checkout -b Gitignore-fix 2f734f3
switched to an earlier commit then created a branch that I used to create a pull request

**Comment by mevolkan** [comment]
this is the command I used git checkout -b Gitignore-fix 2f734f3
switched to an earlier commit then created a branch that I used to create a pull request

**Comment by booleanhunter** [comment]
Sorry for the delay in my replies - I got busy with work!

Hmm, I think I understand why that won't work. The reason being 2-fold:

1. That specific commit still contains changes you made in other files too, not just the gitignore one. Check [this out](https://github.com/mevolkan/how-to-build-your-own-uber-for-x-app/commit/2f734f35de18daf0659437c8b6df1e27d6ead6a3).
2. Moreover, the `git checkout` command doesn't quite reset the branch HEAD to point to that commit - it just assumes as though you were making a new change.

Might I suggest an easier way?

1. Checkout to a new branch using `git checkout -b branch-name`.
2. Do a `git reset --hard b2984af5385a989057388a6bef4354cb3689b7e5`. This is the [commit](https://github.com/mevolkan/how-to-build-your-own-uber-for-x-app/commit/b2984af5385a989057388a6bef4354cb3689b7e5) prior to the changes you introduced. This will have the effect of resetting the branch you're currently in, so that the branch HEAD points to this commit.
3. Now, you can just add a new .gitignore file, and commit that alone and raise a PR. This way, the PR will show only 1 single file added, i.e your gitignore file.

Lemme know if this makes sense?

**Comment by mevolkan** [comment]
Hi Ashwin, no problem
It makes sense, let  me do that

**Pull request closed without merging**
