### PR TITLE
fixed errors with mongo connection string

### PR DESCRIPTION
**Pull request by mevolkan**

### CODE REVIEW

**Comment by mevolkan** [comment]
https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/
issue is highlighted here

**Comment by booleanhunter** [comment]
Hi @mevolkan, thanks for the P.R. It seems like you've unintentionally committed `node_modules` as well.

I just noticed that my project is missing a `.gitignore` file. Do you want to make a separate P.R, and add this file first? You can just copy it from here: https://github.com/booleanhunter-tech-blog/clubhive/blob/master/.gitignore

**Comment by mevolkan** [comment]
sorry about that, didn't notice
let me fix it

**Comment by mevolkan** [comment]
this should be fine

**Comment by booleanhunter** [comment]
@mevolkan Think it would be better to raise separate PRs - one for the gitignore, and another one for the changes for mongo-connection string, and one for the mapbox changes. That way, the commit history will be clean. :) Right now, the PR would have the node_modules added first, and in the next commit it is removed. Please let me know if you need help.

That reminds me, I will also write a contributions guideline. :)

**Comment by mevolkan** [comment]
I will need help with that, first time I'm doing a pull request for such a project
But if i got you correctly, I can just delete this one then make a new one, correct?

**Comment by booleanhunter** [comment]
@mevolkan yes, you can do that. Lets do it step-by-step? You could perhaps begin by raising a P.R for just the gitignore file.

**Comment by mevolkan** [comment]
okay, let me do that

**Pull request closed without merging**
